name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Move to project directory
        run: cd FirstObject

      - name: Grant execute permission for gradlew
        run: chmod +x FirstObject/gradlew

      - name: Build with Gradle
        run: ./FirstObject/gradlew clean build